### ISSUE TITLE
importance_df provided the order but not aboslute_mean_shap value

### ISSUE THREAD

**Issue by ShaunFChen** [TorkamaniLab/zoish#76]
https://github.com/TorkamaniLab/zoish/blob/537d1e403e6c0cfc85bbfa1e7cb1aa7336bb15de/zoish/feature_selectors/shap_selectors.py#L755

importance_df provided the sorted feature index (same content of other attribute) but not aboslute_mean_shap value or feature names

<img width="318" alt="image" src="https://github.com/TorkamaniLab/zoish/assets/38847347/10888809-4c3e-4819-bc9c-0c7490d342b3">

**Comment by drhosseinjavedani** [comment]
Now it has requested information, check examples
