### ISSUE TITLE
Explain the example of usage for arguments in ShapFeatureSelector

### ISSUE THREAD

**Issue by ShaunFChen** [TorkamaniLab/zoish#80]
1. In README and all the notebooks, it assigned a value to `cv` 
https://github.com/TorkamaniLab/zoish/blob/537d1e403e6c0cfc85bbfa1e7cb1aa7336bb15de/README.md?plain=1#L231

However, in the function, it indicated to take **object**:
https://github.com/TorkamaniLab/zoish/blob/537d1e403e6c0cfc85bbfa1e7cb1aa7336bb15de/zoish/feature_selectors/shap_selectors.py#L439

2. What does it mean for `n_iter` (default set to 10) as we assumed the input estimator was optimized already? 
https://github.com/TorkamaniLab/zoish/blob/537d1e403e6c0cfc85bbfa1e7cb1aa7336bb15de/zoish/feature_selectors/shap_selectors.py#L440
(as it's time-consuming - any benefit from it?)

3. The default algorithm is "permutation" but why not "auto” as the default [SHAP TreeExplainer](https://shap-lrjball.readthedocs.io/en/latest/generated/shap.TreeExplainer.html)?
https://github.com/TorkamaniLab/zoish/blob/537d1e403e6c0cfc85bbfa1e7cb1aa7336bb15de/zoish/feature_selectors/shap_selectors.py#L437

**Comment by ShaunFChen** [comment]
Also, what does it mean for `n_iter` (default set to 10) as we assumed the input estimator was optimized already?

**Comment by drhosseinjavedani** [comment]
example added
