### ISSUE TITLE
Zoish on LightGBMClassifier returned all zero shap values for binary classification

### ISSUE THREAD

**Issue by ShaunFChen** [TorkamaniLab/zoish#82]
As titled, the Zoish shapselector would return an all-zero array after explanation of LightGBMClassifier for binary classification. The following code to reproduce the issue was adapted from the example [shap_estimator_optimized_by_gridsearchcv.ipynb](https://github.com/TorkamaniLab/zoish/blob/main/examples/shap/shap_estimator_optimized_by_gridsearchcv.ipynb) while modified from multi-class classification into a binary one.

The issue was very likely caused and related to this post:
[TreeExplainer on LightGBMClassifier returns 2D array of shap values in binary classification case #526](https://github.com/shap/shap/issues/526)
as I also received the message: 
`LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray`

- Notice that it only happened to original shap with zoish but not fasttreeshap with zoish.

[report_shap_zoish_on_lgb_binary_classification.pdf](https://github.com/TorkamaniLab/zoish/files/14103268/report_shap_zoish_on_lgb_binary_classification.pdf)

**Comment by ShaunFChen** [comment]
It's a warning from `shap` 

https://github.com/shap/shap/blob/1b7dead63e18fcbfea7cedc0764f6f45c6c8ff9e/shap/explainers/_tree.py#L429

**Comment by ShaunFChen** [comment]
Can implement a model check without importing the module to switch into a different condition like `shap`

https://github.com/shap/shap/blob/1b7dead63e18fcbfea7cedc0764f6f45c6c8ff9e/shap/explainers/_tree.py#L1133C1-L1135C41

```python
        elif safe_isinstance(model, "lightgbm.sklearn.LGBMClassifier"):
            assert_import("lightgbm")
            self.model_type = "lightgbm"
```

**Comment by drhosseinjavedani** [comment]
problem solved, check these examples https://github.com/TorkamaniLab/zoish/tree/main/examples/shap
